replicaCount: 1

image:
  repository: volodymyr1213/peak6-app
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
  - peak6-app.volodymyr1213.net
  tls: []
 

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
